allowBuilds:
  '@firebase/util': true
  '@google/genai': set this to true or false
  protobufjs: true
  sharp: true
  supabase: true
  unrs-resolver: true
overrides:
  postcss: 8.5.26
  sharp: 0.35.0
