-- SmartBetBot Phase 3: core PostgreSQL schema.
-- Historical facts are retained; destructive cascades are limited to user-owned data.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_updated_at() from public, anon, authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (display_name is null or char_length(display_name) between 2 and 80),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 2048),
  role text not null default 'user' check (role in ('user', 'admin', 'premium', 'analyst')),
  timezone text not null default 'UTC' check (char_length(timezone) between 1 and 64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'Application profile linked one-to-one with auth.users.';
comment on column public.profiles.role is 'Server-managed application role; never writable by end users.';

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create table public.user_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  minimum_smart_score smallint not null default 75 check (minimum_smart_score between 0 and 100),
  minimum_probability numeric(6,5) not null default 0.75 check (minimum_probability between 0 and 1),
  minimum_edge numeric(7,6) not null default 0.05 check (minimum_edge between -1 and 1),
  live_enabled boolean not null default true,
  prematch_enabled boolean not null default true,
  markets text[] not null default array[]::text[],
  league_ids uuid[] not null default array[]::uuid[],
  quiet_hours_enabled boolean not null default false,
  quiet_hours_start time,
  quiet_hours_end time,
  timezone text not null default 'UTC' check (char_length(timezone) between 1 and 64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_quiet_hours_complete check (
    not quiet_hours_enabled or (quiet_hours_start is not null and quiet_hours_end is not null)
  )
);

comment on table public.user_preferences is 'Per-user signal and notification preferences.';

create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

create table public.sports (
  id smallint generated by default as identity primary key,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger sports_set_updated_at
before update on public.sports
for each row execute function public.set_updated_at();

create table public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique check (code is null or code ~ '^[A-Z]{2,3}$'),
  flag_url text check (flag_url is null or char_length(flag_url) <= 2048),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger countries_set_updated_at
before update on public.countries
for each row execute function public.set_updated_at();

create table public.leagues (
  id uuid primary key default gen_random_uuid(),
  sport_id smallint not null references public.sports(id) on delete restrict,
  country_id bigint references public.countries(id) on delete set null,
  provider text not null,
  provider_id bigint not null,
  name text not null,
  league_type text not null default 'league' check (league_type in ('league', 'cup', 'friendly')),
  logo_url text check (logo_url is null or char_length(logo_url) <= 2048),
  coverage jsonb not null default '{}'::jsonb check (jsonb_typeof(coverage) = 'object'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_id)
);

create index leagues_sport_active_idx on public.leagues (sport_id, is_active);
create index leagues_country_idx on public.leagues (country_id) where country_id is not null;

create trigger leagues_set_updated_at
before update on public.leagues
for each row execute function public.set_updated_at();

create table public.seasons (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete cascade,
  season_year smallint not null check (season_year between 1900 and 2200),
  starts_on date,
  ends_on date,
  is_current boolean not null default false,
  coverage jsonb not null default '{}'::jsonb check (jsonb_typeof(coverage) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season_year),
  constraint seasons_date_order check (starts_on is null or ends_on is null or starts_on <= ends_on)
);

create unique index seasons_one_current_per_league_idx
on public.seasons (league_id) where is_current;

create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_updated_at();

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  country_id bigint references public.countries(id) on delete set null,
  provider text not null,
  provider_id bigint not null,
  name text not null,
  code text check (code is null or char_length(code) <= 12),
  logo_url text check (logo_url is null or char_length(logo_url) <= 2048),
  founded_year smallint check (founded_year is null or founded_year between 1800 and 2200),
  venue jsonb not null default '{}'::jsonb check (jsonb_typeof(venue) = 'object'),
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_id)
);

create index teams_country_idx on public.teams (country_id) where country_id is not null;

create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

create table public.fixtures (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.leagues(id) on delete restrict,
  season_id uuid references public.seasons(id) on delete set null,
  home_team_id uuid not null references public.teams(id) on delete restrict,
  away_team_id uuid not null references public.teams(id) on delete restrict,
  provider text not null,
  provider_id bigint not null,
  kickoff_at timestamptz not null,
  status text not null default 'scheduled' check (
    status in ('scheduled', 'live', 'halftime', 'finished', 'postponed', 'cancelled', 'abandoned')
  ),
  provider_status text,
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  added_time smallint check (added_time is null or added_time between 0 and 30),
  home_score smallint check (home_score is null or home_score >= 0),
  away_score smallint check (away_score is null or away_score >= 0),
  halftime_home_score smallint check (halftime_home_score is null or halftime_home_score >= 0),
  halftime_away_score smallint check (halftime_away_score is null or halftime_away_score >= 0),
  round text,
  referee text,
  venue jsonb not null default '{}'::jsonb check (jsonb_typeof(venue) = 'object'),
  has_events boolean not null default false,
  has_statistics boolean not null default false,
  has_odds boolean not null default false,
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_id),
  constraint fixtures_distinct_teams check (home_team_id <> away_team_id)
);

create index fixtures_kickoff_idx on public.fixtures (kickoff_at);
create index fixtures_status_kickoff_idx on public.fixtures (status, kickoff_at);
create index fixtures_league_kickoff_idx on public.fixtures (league_id, kickoff_at desc);
create index fixtures_home_team_idx on public.fixtures (home_team_id, kickoff_at desc);
create index fixtures_away_team_idx on public.fixtures (away_team_id, kickoff_at desc);

create trigger fixtures_set_updated_at
before update on public.fixtures
for each row execute function public.set_updated_at();

create table public.fixture_events (
  id bigint generated always as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  team_id uuid references public.teams(id) on delete set null,
  fingerprint text not null,
  provider_event_id text,
  event_type text not null,
  detail text,
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  extra_minute smallint check (extra_minute is null or extra_minute between 0 and 30),
  player_provider_id bigint,
  player_name text,
  assist_provider_id bigint,
  assist_name text,
  comments text,
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  occurred_at timestamptz,
  created_at timestamptz not null default now(),
  unique (fixture_id, fingerprint)
);

create index fixture_events_fixture_minute_idx
on public.fixture_events (fixture_id, match_minute, id);
create index fixture_events_type_idx on public.fixture_events (event_type, created_at desc);

create table public.fixture_stats_snapshots (
  id bigint generated always as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete restrict,
  captured_at timestamptz not null,
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  shots smallint check (shots is null or shots >= 0),
  shots_on_target smallint check (shots_on_target is null or shots_on_target >= 0),
  shots_off_target smallint check (shots_off_target is null or shots_off_target >= 0),
  blocked_shots smallint check (blocked_shots is null or blocked_shots >= 0),
  possession numeric(5,2) check (possession is null or possession between 0 and 100),
  corners smallint check (corners is null or corners >= 0),
  fouls smallint check (fouls is null or fouls >= 0),
  yellow_cards smallint check (yellow_cards is null or yellow_cards >= 0),
  red_cards smallint check (red_cards is null or red_cards >= 0),
  goalkeeper_saves smallint check (goalkeeper_saves is null or goalkeeper_saves >= 0),
  passes_total integer check (passes_total is null or passes_total >= 0),
  passes_accurate integer check (passes_accurate is null or passes_accurate >= 0),
  attacks integer check (attacks is null or attacks >= 0),
  dangerous_attacks integer check (dangerous_attacks is null or dangerous_attacks >= 0),
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  created_at timestamptz not null default now(),
  unique (fixture_id, team_id, captured_at)
);

create index fixture_stats_fixture_captured_idx
on public.fixture_stats_snapshots (fixture_id, captured_at desc);

create table public.odds_snapshots (
  id bigint generated always as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  provider text not null,
  bookmaker text not null,
  market text not null,
  selection text not null,
  line numeric(8,3),
  decimal_odds numeric(10,4) not null check (decimal_odds > 1),
  captured_at timestamptz not null,
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  is_live boolean not null default false,
  stopped boolean not null default false,
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  created_at timestamptz not null default now()
);

create index odds_snapshots_fixture_market_time_idx
on public.odds_snapshots (fixture_id, market, selection, captured_at desc);
create index odds_snapshots_live_time_idx
on public.odds_snapshots (is_live, captured_at desc) where is_live;
create index odds_snapshots_bookmaker_idx
on public.odds_snapshots (bookmaker, market, captured_at desc);

create table public.model_versions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  version text not null,
  model_type text not null,
  status text not null default 'draft' check (status in ('draft', 'validation', 'active', 'retired', 'failed')),
  training_started_at timestamptz,
  training_finished_at timestamptz,
  training_data_cutoff timestamptz,
  feature_schema jsonb not null default '{}'::jsonb check (jsonb_typeof(feature_schema) = 'object'),
  hyperparameters jsonb not null default '{}'::jsonb check (jsonb_typeof(hyperparameters) = 'object'),
  evaluation_metrics jsonb not null default '{}'::jsonb check (jsonb_typeof(evaluation_metrics) = 'object'),
  calibration_metrics jsonb not null default '{}'::jsonb check (jsonb_typeof(calibration_metrics) = 'object'),
  artifact_uri text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, version),
  constraint model_versions_training_order check (
    training_started_at is null or training_finished_at is null or training_started_at <= training_finished_at
  )
);

create unique index model_versions_one_active_per_name_idx
on public.model_versions (name) where is_active;

create trigger model_versions_set_updated_at
before update on public.model_versions
for each row execute function public.set_updated_at();

create table public.predictions (
  id uuid primary key default gen_random_uuid(),
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  model_version_id uuid not null references public.model_versions(id) on delete restrict,
  market text not null,
  selection text not null,
  line numeric(8,3),
  probability numeric(7,6) not null check (probability between 0 and 1),
  calibrated_probability numeric(7,6) check (calibrated_probability is null or calibrated_probability between 0 and 1),
  feature_cutoff_at timestamptz not null,
  features jsonb not null default '{}'::jsonb check (jsonb_typeof(features) = 'object'),
  predicted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index predictions_fixture_market_idx
on public.predictions (fixture_id, market, selection, predicted_at desc);
create index predictions_model_time_idx
on public.predictions (model_version_id, predicted_at desc);

create table public.strategies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  market text not null,
  is_live boolean not null default false,
  enabled boolean not null default false,
  min_probability numeric(7,6) not null default 0.75 check (min_probability between 0 and 1),
  min_edge numeric(7,6) not null default 0.05 check (min_edge between -1 and 1),
  min_smart_score smallint not null default 75 check (min_smart_score between 0 and 100),
  min_data_quality numeric(7,6) not null default 0.70 check (min_data_quality between 0 and 1),
  min_odds numeric(10,4) check (min_odds is null or min_odds > 1),
  max_odds numeric(10,4) check (max_odds is null or max_odds > 1),
  cooldown_seconds integer not null default 300 check (cooldown_seconds >= 0),
  config_json jsonb not null default '{}'::jsonb check (jsonb_typeof(config_json) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint strategies_odds_order check (min_odds is null or max_odds is null or min_odds <= max_odds)
);

create index strategies_enabled_market_idx on public.strategies (enabled, is_live, market);

create trigger strategies_set_updated_at
before update on public.strategies
for each row execute function public.set_updated_at();

create table public.signals (
  id uuid primary key default gen_random_uuid(),
  fixture_id uuid not null references public.fixtures(id) on delete restrict,
  strategy_id uuid not null references public.strategies(id) on delete restrict,
  prediction_id uuid references public.predictions(id) on delete set null,
  model_version_id uuid references public.model_versions(id) on delete restrict,
  signal_type text not null check (signal_type in ('prematch', 'live')),
  market text not null,
  selection text not null,
  line numeric(8,3),
  decimal_odds numeric(10,4) not null check (decimal_odds > 1),
  model_probability numeric(7,6) not null check (model_probability between 0 and 1),
  raw_implied_probability numeric(7,6) not null check (raw_implied_probability between 0 and 1),
  fair_market_probability numeric(7,6) check (fair_market_probability is null or fair_market_probability between 0 and 1),
  edge numeric(8,7) not null check (edge between -1 and 1),
  expected_value numeric(12,7) not null,
  data_quality_score numeric(5,2) not null check (data_quality_score between 0 and 100),
  live_pressure_score numeric(5,2) check (live_pressure_score is null or live_pressure_score between 0 and 100),
  smart_score numeric(5,2) not null check (smart_score between 0 and 100),
  category text not null check (category in ('elite', 'strong', 'qualified', 'watch', 'no_bet')),
  status text not null default 'qualified' check (status in ('qualified', 'suppressed', 'cancelled', 'settled')),
  fingerprint text not null,
  deduplication_key text not null unique,
  triggered_at timestamptz not null default now(),
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  critical_event text,
  created_at timestamptz not null default now()
);

create index signals_fixture_triggered_idx on public.signals (fixture_id, triggered_at desc);
create index signals_status_type_time_idx on public.signals (status, signal_type, triggered_at desc);
create index signals_strategy_time_idx on public.signals (strategy_id, triggered_at desc);
create index signals_category_time_idx on public.signals (category, triggered_at desc);
create index signals_fingerprint_time_idx on public.signals (fingerprint, triggered_at desc);

create table public.signal_reasons (
  id bigint generated always as identity primary key,
  signal_id uuid not null references public.signals(id) on delete cascade,
  code text not null,
  label text not null,
  numeric_value numeric(16,6),
  text_value text,
  unit text,
  sort_order smallint not null default 0,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  unique (signal_id, code),
  constraint signal_reasons_has_value check (numeric_value is not null or text_value is not null or metadata <> '{}'::jsonb)
);

create index signal_reasons_signal_order_idx on public.signal_reasons (signal_id, sort_order, id);

create table public.signal_results (
  signal_id uuid primary key references public.signals(id) on delete restrict,
  result_status text not null default 'pending' check (result_status in ('won', 'lost', 'void', 'push', 'pending')),
  home_score smallint check (home_score is null or home_score >= 0),
  away_score smallint check (away_score is null or away_score >= 0),
  settled_at timestamptz,
  settlement_odds numeric(10,4) check (settlement_odds is null or settlement_odds > 1),
  stake_units numeric(10,4) not null default 1 check (stake_units > 0),
  profit_loss_units numeric(12,4),
  settlement_details jsonb not null default '{}'::jsonb check (jsonb_typeof(settlement_details) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint signal_results_settlement_state check (
    (result_status = 'pending' and settled_at is null)
    or (result_status <> 'pending' and settled_at is not null)
  )
);

create index signal_results_status_settled_idx on public.signal_results (result_status, settled_at desc);

create trigger signal_results_set_updated_at
before update on public.signal_results
for each row execute function public.set_updated_at();

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  fcm_token text not null,
  device_id text,
  platform text not null default 'web' check (platform in ('web', 'ios', 'android')),
  user_agent text,
  is_enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, fcm_token)
);

create index push_subscriptions_user_enabled_idx
on public.push_subscriptions (user_id, is_enabled);

create trigger push_subscriptions_set_updated_at
before update on public.push_subscriptions
for each row execute function public.set_updated_at();

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  signal_id uuid references public.signals(id) on delete set null,
  title text not null,
  body text not null,
  channel text not null default 'push' check (channel in ('push', 'in_app', 'email')),
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed', 'opened')),
  provider_message_id text,
  error_code text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  sent_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_created_idx on public.notifications (user_id, created_at desc);
create index notifications_queued_idx on public.notifications (status, created_at) where status = 'queued';

create table public.worker_runs (
  id uuid primary key default gen_random_uuid(),
  worker text not null check (worker in ('live', 'odds', 'prematch', 'settlement', 'notification')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running', 'succeeded', 'partial', 'failed')),
  fixtures_processed integer not null default 0 check (fixtures_processed >= 0),
  signals_generated integer not null default 0 check (signals_generated >= 0),
  errors integer not null default 0 check (errors >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  constraint worker_runs_time_order check (finished_at is null or started_at <= finished_at)
);

create index worker_runs_worker_started_idx on public.worker_runs (worker, started_at desc);
create index worker_runs_status_started_idx on public.worker_runs (status, started_at desc);

create table public.api_usage (
  id bigint generated always as identity primary key,
  provider text not null,
  endpoint text not null,
  http_method text not null default 'GET',
  response_status smallint check (response_status is null or response_status between 100 and 599),
  requests_used integer not null default 1 check (requests_used >= 0),
  rate_limit_remaining integer check (rate_limit_remaining is null or rate_limit_remaining >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  request_id text,
  worker text,
  fixture_id uuid references public.fixtures(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  requested_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index api_usage_provider_time_idx on public.api_usage (provider, requested_at desc);
create index api_usage_worker_time_idx on public.api_usage (worker, requested_at desc) where worker is not null;

create table public.audit_logs (
  id bigint generated always as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  request_id text,
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

comment on table public.audit_logs is 'Append-only operational audit trail. Secrets and complete tokens are forbidden.';

create index audit_logs_actor_time_idx on public.audit_logs (actor_user_id, created_at desc);
create index audit_logs_entity_time_idx on public.audit_logs (entity_type, entity_id, created_at desc);
create index audit_logs_action_time_idx on public.audit_logs (action, created_at desc);
